version: '3'
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7396
      - POSTGRES_DB=db_tp
      - PG_TRUST_LOCALNET=true
      - DB_PASS=7396
    ports:
      - "5433:5433"
  web:
    depends_on:
      - db
    links:
      - db
    build: .
    ports:
      - "8080:8080"
    restart: always